# Generated by Django 5.2.17 on 2026-08-22 17:07

import apps.common.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('contacts', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=16)),
                ('automation_paused_until', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('channel_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='channels.channelconnection')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='contacts.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'messaging_conversation',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=3)),
                ('source', models.CharField(blank=True, choices=[('automation', 'Automation'), ('agent', 'Agent'), ('api', 'API'), ('broadcast', 'Broadcast'), ('sequence', 'Sequence')], default='', max_length=16)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('error', models.CharField(blank=True, default='', max_length=200)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('internal', models.BooleanField(default=False)),
                ('channel_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channels.channelconnection')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'messaging_message',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContactChannelIdentity',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('messenger', 'Facebook Messenger'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], max_length=30)),
                ('platform_user_id', models.CharField(max_length=200)),
                ('opt_in', models.BooleanField(default=False)),
                ('opt_in_at', models.DateTimeField(blank=True, null=True)),
                ('opt_in_source', models.CharField(blank=True, choices=[('message_in', 'Inbound message'), ('data_collection', 'Data collection'), ('import', 'Import'), ('api', 'API'), ('manual', 'Manual')], default='', max_length=32)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('window_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('channel_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='channels.channelconnection')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_identities', to='contacts.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'messaging_contact_channel_identity',
                'indexes': [models.Index(fields=['contact'], name='identity_contact_idx'), models.Index(fields=['workspace', 'platform', 'window_expires_at'], name='identity_ws_plat_win_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('channel_connection__isnull', False)), fields=('channel_connection', 'platform_user_id'), name='identity_unique_conn_user'), models.UniqueConstraint(condition=models.Q(('channel_connection__isnull', True)), fields=('workspace', 'platform', 'platform_user_id'), name='identity_unique_pending'), models.CheckConstraint(condition=models.Q(('opt_in', False), models.Q(('opt_in_at__isnull', False), models.Q(('opt_in_source', ''), _negated=True)), _connector='OR'), name='identity_optin_is_audited')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['workspace', 'state', 'last_message_at'], name='conv_ws_state_last_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('contact', 'channel_connection'), name='conv_unique_contact_conn'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='message_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['workspace', 'status'], name='message_ws_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('conversation', 'idempotency_key'), name='message_unique_conv_idem'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_message_id', ''), _negated=True), fields=('channel_connection', 'provider_message_id'), name='message_unique_conn_provider'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'in'), ('source', '')), models.Q(('direction', 'out'), models.Q(('source', ''), _negated=True)), _connector='OR'), name='message_source_matches_direction'),
        ),
    ]
