# Generated by Django 5.2.17 on 2026-08-22 17:40

import apps.common.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='send_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SendBucket',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tokens', models.FloatField(default=0.0)),
                ('capacity', models.FloatField()),
                ('refill_rate', models.FloatField()),
                ('refilled_at', models.DateTimeField()),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='send_bucket', to='channels.channelconnection')),
            ],
            options={
                'db_table': 'messaging_send_bucket',
                'constraints': [models.CheckConstraint(condition=models.Q(('refill_rate__gt', 0)), name='bucket_rate_positive'), models.CheckConstraint(condition=models.Q(('tokens__gte', 0)), name='bucket_tokens_nonneg')],
            },
        ),
    ]
