# Generated by Django 5.2.17 on 2026-08-23 11:17

import apps.common.encryption
import apps.common.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundWebhook',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(help_text='HTTPS endpoint that receives deliveries.', max_length=500)),
                ('secret', apps.common.encryption.EncryptedTextField(help_text='Shared secret the receiver verifies X-BrightBean-Signature with.')),
                ('events', models.JSONField(default=list, help_text='Catalog event names this endpoint subscribes to.')),
                ('enabled', models.BooleanField(default=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0, help_text='Deliveries that exhausted their retries since the last success. Reset to 0 on any success.')),
                ('disabled_at', models.DateTimeField(blank=True, help_text='When the failure counter switched this endpoint off. Cleared when an operator re-enables it.', null=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'api_outbound_webhook',
                'ordering': ['url'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('blocked', 'Blocked')], max_length=20)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, help_text='Null when the receiver was never reached — DNS, timeout, or the SSRF guard.', null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='', help_text='Scrubbed and capped; see MAX_STORED_ERROR_CHARS.')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.outboundwebhook')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'api_webhook_delivery',
                'ordering': ['-created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Human label, e.g. "Zapier scenario".', max_length=100)),
                ('scopes', models.JSONField(default=list, help_text='Subset of ApiScope. See apps.api.auth.SCOPE_PERMISSIONS for what each grants.')),
                ('lookup_prefix', models.CharField(db_index=True, help_text='Non-secret handle derived from the token; the indexed half of verification.', max_length=16)),
                ('token_digest', models.CharField(help_text="HMAC of the token's secret part. The stored half; the plaintext is never persisted.", max_length=64, unique=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text="Audit only. The key outlives this user's membership by design; see the class docstring.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_api_keys', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'api_api_key',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'revoked_at'], name='apikey_ws_revoked_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='outboundwebhook',
            index=models.Index(fields=['workspace', 'enabled'], name='outboundwebhook_ws_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['webhook', '-created_at'], name='webhookdelivery_hook_time_idx'),
        ),
    ]
