# Generated by Django 5.2.17 on 2026-10-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdelivery',
            name='response_code',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Null when the receiver was never reached because of DNS, timeout, or the SSRF guard.', null=True),
        ),
    ]
