# Generated by Django 5.2.17 on 2026-08-23 19:46

import apps.common.uuid7
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_contact_contact_ws_created_idx'),
        ('flows', '0005_handledcomment_public_reply_sent_at'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'campaigns_sequence',
                'ordering': ['name'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SequenceEnrollment',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('unsubscribed', 'Unsubscribed')], default='active', max_length=16)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_enrollments', to='contacts.contact')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='campaigns.sequence')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'campaigns_sequence_enrollment',
                'ordering': ['-created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(help_text='1-based rung number. Contiguous within a sequence.')),
                ('delay_value', models.PositiveIntegerField(default=1)),
                ('delay_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='days', max_length=16)),
                ('send_window', models.JSONField(blank=True, default=dict, help_text="SPEC §11.5's shape: {enabled, days[], from, to, use_contact_timezone}.")),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequence_steps', to='flows.flow')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='campaigns.sequence')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'campaigns_sequence_step',
                'ordering': ['position'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RuleTriggerFire',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_fired_at', models.DateTimeField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_trigger_fires', to='contacts.contact')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_fires', to='flows.trigger')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'campaigns_rule_trigger_fire',
                'constraints': [models.UniqueConstraint(fields=('trigger', 'contact'), name='rulefire_unique_trigger_contact')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='sequence',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('workspace'), name='sequence_unique_name_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='sequenceenrollment',
            index=models.Index(fields=['status', 'next_run_at'], name='enrollment_due_idx'),
        ),
        migrations.AddIndex(
            model_name='sequenceenrollment',
            index=models.Index(fields=['workspace', 'sequence'], name='enrollment_ws_sequence_idx'),
        ),
        migrations.AddConstraint(
            model_name='sequenceenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('sequence', 'contact'), name='enrollment_one_active_per_contact'),
        ),
        migrations.AddConstraint(
            model_name='sequencestep',
            constraint=models.UniqueConstraint(fields=('sequence', 'position'), name='step_unique_position_per_sequence'),
        ),
    ]
