# Generated by Django 5.2.17 on 2026-09-13 19:42
"""The three billing tables.

Two are organization-level and one is tenant data. All three stay empty on a
deployment with no Stripe configuration, which is the default and the supported
state for a self-hoster — see ``apps/billing/apps.py`` for why the app installs
unconditionally anyway.

``ActiveContactMonth`` carries a denormalised ``organization_id`` beside the
workspace FK it inherits. That is the one column here that exists for
performance: the active-contact limit is an organization-wide count consulted
before every send, and without it that count is a loop over the organization's
workspaces on the hot path.
"""


import apps.common.uuid7
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0005_erasure_one_live_per_contact'),
        ('organizations', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCustomer',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_customer_id', models.CharField(max_length=64, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(default='none', max_length=32)),
                ('price_id', models.CharField(blank=True, default='', max_length=64)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('checkout_pending_since', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='organizations.organization')),
            ],
            options={
                'db_table': 'billing_customer',
            },
        ),
        migrations.CreateModel(
            name='ActiveContactMonth',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=7)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_months', to='contacts.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_contact_months', to='organizations.organization')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'billing_active_contact_month',
                'indexes': [models.Index(fields=['organization', 'period'], name='activecontact_org_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('contact', 'period'), name='activecontactmonth_unique_period')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StripeEventLog',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=20)),
                ('raw', models.JSONField(blank=True, default=dict, help_text="Stripe's payload for this event, as delivered. Capped at MAX_RAW_BYTES.")),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='billing.billingcustomer')),
            ],
            options={
                'db_table': 'billing_stripe_event_log',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['-received_at'], name='stripeevent_recv_idx')],
            },
        ),
    ]
