# Generated by Django 5.2.17 on 2026-08-21 20:51

import apps.common.uuid7
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('locale', models.CharField(blank=True, default='', max_length=16)),
                ('timezone', models.CharField(blank=True, default='', max_length=63)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=16)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'contacts_contact',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'Date and time'), ('boolean', 'True or false')], max_length=16)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'contacts_custom_field',
                'ordering': ['name'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_text', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='contacts.contact')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='contacts.customfield')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'contacts_custom_field_value',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('filter_json', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'contacts_segment',
                'ordering': ['name'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'contacts_tag',
                'ordering': ['name'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='contacts.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='contacts.tag')),
            ],
            options={
                'db_table': 'contacts_contact_tag',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts', through='contacts.ContactTag', to='contacts.tag'),
        ),
        migrations.AddConstraint(
            model_name='customfield',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('workspace'), name='customfield_unique_name_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['workspace', 'field', 'contact'], name='cfv_ws_field_contact_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(fields=('contact', 'field'), name='customfieldvalue_unique_contact_field'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value_text__isnull', False), ('value_number__isnull', True), ('value_date__isnull', True), ('value_datetime__isnull', True), ('value_bool__isnull', True)), models.Q(('value_number__isnull', False), ('value_text__isnull', True), ('value_date__isnull', True), ('value_datetime__isnull', True), ('value_bool__isnull', True)), models.Q(('value_date__isnull', False), ('value_text__isnull', True), ('value_number__isnull', True), ('value_datetime__isnull', True), ('value_bool__isnull', True)), models.Q(('value_datetime__isnull', False), ('value_text__isnull', True), ('value_number__isnull', True), ('value_date__isnull', True), ('value_bool__isnull', True)), models.Q(('value_bool__isnull', False), ('value_text__isnull', True), ('value_number__isnull', True), ('value_date__isnull', True), ('value_datetime__isnull', True)), _connector='OR'), name='customfieldvalue_exactly_one_value'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('workspace'), name='segment_unique_name_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('workspace'), name='tag_unique_name_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='contacttag',
            index=models.Index(fields=['workspace', 'tag', 'contact'], name='contacttag_ws_tag_contact_idx'),
        ),
        migrations.AddConstraint(
            model_name='contacttag',
            constraint=models.UniqueConstraint(fields=('contact', 'tag'), name='contacttag_unique_contact_tag'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'last_interaction_at'], name='contact_ws_last_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'status'], name='contact_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'email'], name='contact_ws_email_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'phone'], name='contact_ws_phone_idx'),
        ),
    ]
