# Generated by Django 5.2.17 on 2026-08-22 21:37

import apps.common.uuid7
import apps.contacts.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactImport',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=512, upload_to=apps.contacts.models.import_upload_to)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Checking'), ('validated', 'Checked'), ('importing', 'Importing'), ('done', 'Finished'), ('failed', 'Failed')], default='uploaded', max_length=16)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('dedupe', models.CharField(choices=[('update', 'Update the contact that is already there'), ('create', 'Create a second contact anyway'), ('skip', 'Skip the row')], default='update', max_length=16)),
                ('consent_ack', models.BooleanField(default=False)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('next_offset', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_imports', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'contacts_contact_import',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'finished_at'], name='contactimport_status_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
