# Generated by Django 5.2.17 on 2026-08-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactimport'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', '-created_at'], name='contact_ws_created_idx'),
        ),
    ]
