# Generated by Django 5.2.17 on 2026-08-24 12:26

import apps.common.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_contact_ws_created_idx'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactErasure',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_id', models.UUIDField(db_index=True)),
                ('requested_by_label', models.CharField(blank=True, default='', max_length=254)),
                ('source', models.CharField(choices=[('ui', 'Contact page'), ('bulk', 'Bulk action'), ('api', 'Public API')], max_length=8)),
                ('api_key_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=8)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('requested_by', models.ForeignKey(blank=True, help_text='Audit only. Null once the account goes; see requested_by_label.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_erasures', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'contacts_contact_erasure',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='erasure_ws_created_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
