# Generated by Django 5.2.17 on 2026-08-24 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contacterasure'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contacterasure',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'running'))), fields=('workspace', 'contact_id'), name='erasure_one_live_per_contact'),
        ),
    ]
