# Generated by Django 5.2.17 on 2026-08-23 20:20

import apps.common.uuid7
import apps.common.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
        ('messaging', '0003_deleted_status_and_comment_consent'),
        ('queueing', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLabel',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(blank=True, default='#64748B', max_length=7, validators=[apps.common.validators.validate_hex_color])),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'inbox_conversation_label',
                'ordering': ['name'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ConversationLabelLink',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_conversation_labels', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_links', to='messaging.conversation')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='inbox.conversationlabel')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'inbox_conversation_label_link',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InboxReminder',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('remind_at', models.DateTimeField()),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='queueing.scheduledaction')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='messaging.conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_reminders', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'inbox_reminder',
                'ordering': ['remind_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InboxRule',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('condition_json', models.JSONField(blank=True, default=dict)),
                ('actions_json', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'inbox_rule',
                'ordering': ['priority', 'name'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InboxRuleApplication',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_ref', models.CharField(max_length=64)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_applications', to='messaging.conversation')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='inbox.inboxrule')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'inbox_rule_application',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledReply',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('send_at', models.DateTimeField()),
                ('error', models.CharField(blank=True, default='', max_length=200)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='queueing.scheduledaction')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_replies', to='messaging.conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.message')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'inbox_scheduled_reply',
                'ordering': ['send_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='conversationlabel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('workspace'), name='label_unique_name_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='conversationlabellink',
            index=models.Index(fields=['workspace', 'label'], name='labellink_ws_label_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationlabellink',
            constraint=models.UniqueConstraint(fields=('conversation', 'label'), name='labellink_unique_conv_label'),
        ),
        migrations.AddIndex(
            model_name='inboxreminder',
            index=models.Index(fields=['workspace', 'conversation', 'status'], name='reminder_ws_conv_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxrule',
            index=models.Index(fields=['workspace', 'enabled', 'priority'], name='inboxrule_ws_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxruleapplication',
            index=models.Index(fields=['workspace', 'rule'], name='ruleapp_ws_rule_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboxruleapplication',
            constraint=models.UniqueConstraint(fields=('conversation', 'rule', 'event_ref'), name='ruleapp_unique_conv_rule_event'),
        ),
        migrations.AddIndex(
            model_name='scheduledreply',
            index=models.Index(fields=['workspace', 'conversation', 'status'], name='schedreply_ws_conv_status_idx'),
        ),
    ]
