# Generated by Django 5.2.17 on 2026-08-23 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_labels_rules_and_deferred_work'),
        ('messaging', '0003_deleted_status_and_comment_consent'),
        ('queueing', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxreminder',
            name='arm_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inboxreminder',
            name='compose_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='scheduledreply',
            name='arm_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduledreply',
            name='compose_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='inboxreminder',
            constraint=models.UniqueConstraint(condition=models.Q(('compose_token__gt', '')), fields=('workspace', 'compose_token'), name='reminder_unique_compose_token'),
        ),
        migrations.AddConstraint(
            model_name='scheduledreply',
            constraint=models.UniqueConstraint(condition=models.Q(('compose_token__gt', '')), fields=('workspace', 'compose_token'), name='schedreply_unique_compose_token'),
        ),
    ]
