# Generated by Django 5.2.17 on 2026-08-21 06:32

import apps.common.encryption
import apps.common.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCredential',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('messenger', 'Facebook Messenger'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], max_length=30)),
                ('credentials', apps.common.encryption.EncryptedJSONField(default=dict, help_text='Encrypted JSON of platform-specific credential fields.')),
                ('is_configured', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_credentials', to='organizations.organization')),
            ],
            options={
                'db_table': 'credentials_platform_credential',
                'ordering': ['platform'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'platform'), name='platformcredential_unique_org_platform')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceCredentialOverride',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('messenger', 'Facebook Messenger'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], max_length=30)),
                ('credentials', apps.common.encryption.EncryptedJSONField(default=dict, help_text='Encrypted JSON of platform-specific credential fields.')),
                ('is_configured', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'credentials_workspace_credential_override',
                'ordering': ['platform'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'platform'), name='workspacecredentialoverride_unique_workspace_platform')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
