# Generated by Django 5.2.17 on 2026-08-21 20:44

import apps.common.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledAction',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_id', models.UUIDField(blank=True, null=True)),
                ('run_at', models.DateTimeField(help_text='Earliest moment a worker may claim this row.')),
                ('type', models.CharField(help_text='Handler key; see apps.queueing.registry.', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('last_error', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('workspace', models.ForeignKey(blank=True, help_text='NULL for deployment-level system jobs (housekeeping). No tenant query can see those.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_actions', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'queueing_scheduled_action',
                'ordering': ['run_at'],
                'indexes': [models.Index(fields=['status', 'run_at'], name='scheduledaction_status_run_idx'), models.Index(fields=['contact_id', 'status'], name='scheduledaction_contact_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
