# Generated by Django 5.2.17 on 2026-08-21 06:32

import apps.common.uuid7
import apps.common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='', help_text='A single emoji, shown in the switcher.', max_length=8)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('timezone', models.CharField(blank=True, default='', max_length=63)),
                ('primary_color', models.CharField(blank=True, default='', max_length=7, validators=[apps.common.validators.validate_hex_color])),
                ('secondary_color', models.CharField(blank=True, default='', max_length=7, validators=[apps.common.validators.validate_hex_color])),
                ('is_archived', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='organizations.organization')),
            ],
            options={
                'db_table': 'workspaces_workspace',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='workspace_unique_name_per_org')],
            },
        ),
    ]
