# Generated by Django 5.2.17 on 2026-08-21 20:51

import apps.common.uuid7
import apps.flows.schema.envelope
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('folder', models.CharField(blank=True, default='', max_length=200)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FlowVersion',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('graph_json', models.JSONField(default=apps.flows.schema.envelope.empty_graph)),
                ('published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='flows.flow')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-version'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['workspace', 'status'], name='flows_flow_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['workspace', 'folder'], name='flows_flow_ws_folder_idx'),
        ),
        migrations.AddIndex(
            model_name='flowversion',
            index=models.Index(fields=['flow', '-version'], name='flows_version_latest_idx'),
        ),
        migrations.AddConstraint(
            model_name='flowversion',
            constraint=models.UniqueConstraint(fields=('flow', 'version'), name='flows_version_unique_per_flow'),
        ),
        migrations.AddConstraint(
            model_name='flowversion',
            constraint=models.UniqueConstraint(condition=models.Q(('published', True)), fields=('flow',), name='flows_one_published_version_per_flow'),
        ),
    ]
