# Generated by Django 5.2.17 on 2026-08-22 16:58

import apps.common.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('contacts', '0001_initial'),
        ('flows', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowExecution',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('waiting_reply', 'Waiting for a reply'), ('waiting_delay', 'Waiting for a delay'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='running', max_length=16)),
                ('current_node_id', models.CharField(blank=True, default='', max_length=64)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('blocks_since_pause', models.PositiveIntegerField(default=0)),
                ('wait_config', models.JSONField(blank=True, default=dict)),
                ('started_by', models.CharField(blank=True, default='', max_length=100)),
                ('preview', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, default='')),
                ('channel_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_executions', to='channels.channelconnection')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_executions', to='contacts.contact')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='flows.flow')),
                ('flow_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='flows.flowversion')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'flows_flow_execution',
                'indexes': [models.Index(fields=['status', 'updated_at'], name='flowexec_status_updated_idx'), models.Index(fields=['workspace', 'contact', 'status'], name='flowexec_ws_contact_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['running', 'waiting_delay', 'waiting_reply'])), fields=('contact', 'flow'), name='flows_one_live_execution_per_contact_flow')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
