# Generated by Django 5.2.17 on 2026-08-22 21:48

import apps.common.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('contacts', '0001_initial'),
        ('flows', '0002_flowexecution'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('keyword', 'Keyword'), ('comment', 'Comment'), ('story_mention', 'Story mention'), ('story_reply', 'Story reply'), ('follow', 'New follower'), ('ref_url', 'Ref URL'), ('default_reply', 'Default reply'), ('welcome', 'Welcome'), ('rule', 'Rule'), ('api', 'API')], max_length=20)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('channel_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='channels.channelconnection')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='flows.flow')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'flows_trigger',
                'ordering': ['priority', 'created_at', 'id'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HandledComment',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_id', models.CharField(max_length=200)),
                ('post_id', models.CharField(max_length=200)),
                ('commenter_ref', models.CharField(max_length=200)),
                ('commented_at', models.DateTimeField()),
                ('once_per_contact_per_post', models.BooleanField(default=True)),
                ('private_reply_sent_at', models.DateTimeField(blank=True, null=True)),
                ('channel_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handled_comments', to='channels.channelconnection')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_comments', to='contacts.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_comments', to='flows.trigger')),
            ],
            options={
                'db_table': 'flows_handled_comment',
                'ordering': ['-commented_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DefaultReplyState',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sent_at', models.DateTimeField()),
                ('channel_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_reply_states', to='channels.channelconnection')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_reply_states', to='contacts.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'flows_default_reply_state',
                'ordering': ['-last_sent_at'],
                'indexes': [models.Index(fields=['last_sent_at'], name='flows_defaultreply_sent_idx')],
                'constraints': [models.UniqueConstraint(fields=('contact', 'channel_connection'), name='flows_defaultreply_one_per_contact_channel')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RoutedEvent',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_event_id', models.CharField(max_length=200)),
                ('stage', models.CharField(max_length=32)),
                ('outcome', models.CharField(blank=True, default='', max_length=64)),
                ('channel_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routed_events', to='channels.channelconnection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'flows_routed_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='flows_routedevent_ws_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel_connection', 'provider_event_id'), name='flows_routedevent_unique_conn_event')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='trigger',
            index=models.Index(fields=['workspace', 'type', 'enabled'], name='flows_trigger_ws_type_idx'),
        ),
        migrations.AddIndex(
            model_name='trigger',
            index=models.Index(fields=['flow', 'priority'], name='flows_trigger_flow_prio_idx'),
        ),
        migrations.AddConstraint(
            model_name='trigger',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 0)), name='flows_trigger_priority_non_negative'),
        ),
        migrations.AddIndex(
            model_name='handledcomment',
            index=models.Index(fields=['workspace', 'post_id'], name='flows_hcomment_ws_post_idx'),
        ),
        migrations.AddIndex(
            model_name='handledcomment',
            index=models.Index(fields=['commented_at'], name='flows_hcomment_commented_idx'),
        ),
        migrations.AddConstraint(
            model_name='handledcomment',
            constraint=models.UniqueConstraint(fields=('channel_connection', 'comment_id'), name='flows_handledcomment_unique_comment'),
        ),
        migrations.AddConstraint(
            model_name='handledcomment',
            constraint=models.UniqueConstraint(condition=models.Q(('once_per_contact_per_post', True)), fields=('channel_connection', 'post_id', 'commenter_ref'), name='flows_handledcomment_once_per_commenter_per_post'),
        ),
    ]
