# Generated by Django 5.2.17 on 2026-08-24 12:26

import apps.common.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0005_handledcomment_public_reply_sent_at'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowImport',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.JSONField(default=dict)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Awaiting confirmation'), ('applied', 'Imported'), ('discarded', 'Discarded')], default='pending', max_length=16)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'flows_flow_import',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='flows_import_ws_status_idx'), models.Index(fields=['status', 'created_at'], name='flows_import_swept_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
