# Generated by Django 5.2.17 on 2026-10-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0006_flowimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowversion',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Stamps the versions that are live today, so taking one of them offline
        # leaves it frozen rather than editable (services.save_draft). Only a
        # flow's latest version is ever edited in place, and a live flow's latest
        # version is its published one; older versions are never written again,
        # so they need no stamp. publish() writes updated_at when it sets the
        # flag, so it is the moment the version went live.
        migrations.RunSQL(
            "UPDATE flows_flowversion SET published_at = updated_at WHERE published",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='flow',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('offline', 'Offline'), ('archived', 'Archived')], default='draft', max_length=16),
        ),
    ]
