/**
 * Copy the pinned runtime libraries out of node_modules into static/js/vendor/.
 *
 * The copies are committed, so `manage.py runserver` works from a clean clone
 * with no Node installed at all — the same property Studio's checked-in
 * static/js has. Declaring the libraries in package.json on top of that is what
 * `npm audit` and Dependabot read, and CI re-runs this script and diffs the
 * result, so a committed bundle can never drift from its pin.
 *
 * Nothing here reaches the network: it is a file copy out of an already
 * installed tree.
 */
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "static", "js", "vendor");

/**
 * `to` is the committed filename. `from` is the path inside the package.
 *
 * `issue` records which workstream actually consumes the file, so a reviewer
 * can tell a deliberately-early vendoring from dead weight. All of them are
 * vendored now because deviation 6 of the L1-B brief is about closing the door
 * on CDN origins in the CSP, not about what this PR happens to load.
 */
const ASSETS = [
  { pkg: "htmx.org", from: "dist/htmx.min.js", to: "htmx.min.js", issue: "L1-B (loaded by base.html)" },
  { pkg: "alpinejs", from: "dist/cdn.min.js", to: "alpine.min.js", issue: "L1-B (loaded by base.html)" },
  { pkg: "flatpickr", from: "dist/flatpickr.min.js", to: "flatpickr.min.js", issue: "L6-B broadcasts scheduling" },
  { pkg: "flatpickr", from: "dist/flatpickr.min.css", to: "flatpickr.min.css", issue: "L6-B broadcasts scheduling" },
  { pkg: "chart.js", from: "dist/chart.umd.js", to: "chart.umd.min.js", issue: "L7-A analytics" },
  { pkg: "sortablejs", from: "Sortable.min.js", to: "sortable.min.js", issue: "L3-C flow builder" },
];

/**
 * Strip the trailing sourceMappingURL comment.
 *
 * Django's ManifestStaticFilesStorage rewrites `//# sourceMappingURL=` in every
 * .js it collects and raises when the referenced .map is missing — which would
 * fail the Docker build at collectstatic. Shipping the maps instead would add
 * megabytes of debug data to the image for no benefit at runtime.
 */
function stripSourceMap(source) {
  return source.replace(/^\s*\/\/[#@]\s*sourceMappingURL=.*$/gm, "").replace(/\s+$/, "") + "\n";
}

function version(pkg) {
  return JSON.parse(readFileSync(join(ROOT, "node_modules", pkg, "package.json"), "utf8")).version;
}

mkdirSync(OUT, { recursive: true });

const manifest = [];
for (const asset of ASSETS) {
  const source = readFileSync(join(ROOT, "node_modules", asset.pkg, asset.from), "utf8");
  const body = asset.to.endsWith(".js") ? stripSourceMap(source) : source.replace(/\s+$/, "") + "\n";
  writeFileSync(join(OUT, asset.to), body);
  manifest.push({
    file: asset.to,
    package: asset.pkg,
    version: version(asset.pkg),
    sha256: createHash("sha256").update(body).digest("hex"),
    consumer: asset.issue,
  });
  process.stdout.write(`vendored ${asset.to} <- ${asset.pkg}@${manifest.at(-1).version}\n`);
}

// A committed record of what each blob is, so a reader of static/js/vendor/
// never has to guess a version from minified source.
writeFileSync(
  join(OUT, "VENDOR.json"),
  JSON.stringify(
    { note: "Generated by scripts/vendor-js.mjs. Do not edit by hand; run `npm run vendor`.", assets: manifest },
    null,
    2,
  ) + "\n",
);
