# Generated by Django 5.2.17 on 2026-08-24 12:15

import apps.common.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flows', '0005_handledcomment_public_reply_sent_at'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSettings',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wrap_email_links', models.BooleanField(default=False)),
                ('open_pixel', models.BooleanField(default=False)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_settings', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'analytics_tracking_settings',
            },
        ),
        migrations.CreateModel(
            name='NodeStatDaily',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_id', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('sent', models.PositiveIntegerField(default=0)),
                ('delivered', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('clicked', models.PositiveIntegerField(default=0)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_stats', to='flows.flow')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'analytics_node_stat_daily',
                'indexes': [models.Index(fields=['flow', 'date'], name='node_stat_flow_date_idx'), models.Index(fields=['workspace', 'date'], name='node_stat_ws_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('flow', 'node_id', 'date'), name='node_stat_unique_flow_node_date')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
