# Generated by Django 5.2.17 on 2026-08-21 20:59

import apps.common.encryption
import apps.common.uuid7
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConnection',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('messenger', 'Facebook Messenger'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], max_length=30)),
                ('display_name', models.CharField(max_length=200)),
                ('external_id', models.CharField(help_text='Page id, IG user id, WABA phone number id, bot id, Twilio number or sending domain.', max_length=200)),
                ('credentials', apps.common.encryption.EncryptedJSONField(blank=True, default=dict, help_text="Encrypted JSON of the platform's per-connection credentials.")),
                ('status', models.CharField(choices=[('active', 'Active'), ('needs_reauth', 'Needs reconnection'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('capabilities_cache', models.JSONField(blank=True, default=dict, help_text='What the platform reported this specific connection can do. The static table in apps.channels.capabilities is the default; this narrows it per connection where a platform says so (an unverified WhatsApp number, a page without messaging permissions).')),
                ('webhook_secret', apps.common.encryption.EncryptedTextField(blank=True, default='')),
                ('webhook_secret_digest', models.CharField(blank=True, default='', help_text='HMAC of webhook_secret. The queryable half; see the module docstring.', max_length=64)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'channels_channel_connection',
                'ordering': ['platform', 'display_name'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('messenger', 'Facebook Messenger'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], max_length=30)),
                ('provider_event_id', models.CharField(max_length=200)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('skipped_duplicate', 'Skipped (duplicate)'), ('failed', 'Failed')], default='received', max_length=20)),
                ('raw', models.JSONField(blank=True, default=dict, help_text="The provider's payload for this event, as delivered. Attacker-controlled: escape on render.")),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='channels.channelconnection')),
            ],
            options={
                'db_table': 'channels_webhook_event_log',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='channelconnection',
            index=models.Index(fields=['workspace', 'platform'], name='channelconn_ws_platform_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelconnection',
            constraint=models.UniqueConstraint(fields=('platform', 'external_id'), name='channelconnection_unique_platform_ext'),
        ),
        migrations.AddConstraint(
            model_name='channelconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('webhook_secret_digest__gt', '')), fields=('webhook_secret_digest',), name='channelconnection_unique_webhook_digest'),
        ),
        migrations.AddIndex(
            model_name='webhookeventlog',
            index=models.Index(fields=['connection', '-received_at'], name='webhookevent_conn_recv_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookeventlog',
            constraint=models.UniqueConstraint(fields=('connection', 'provider_event_id'), name='webhookeventlog_unique_connection_event'),
        ),
    ]
