# Generated by Django 5.2.17 on 2026-08-22 21:48

import apps.common.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('flows', '0002_flowexecution'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowPreviewLink',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handle_digest', models.CharField(help_text='HMAC of the deep-link handle. The queryable half; see the class docstring.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('chat_id', models.CharField(blank=True, default='', help_text='The Telegram chat that claimed this link. Empty until the first /start.', max_length=200)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('channel_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_links', to='channels.channelconnection')),
                ('created_by', models.ForeignKey(help_text="The editor who pressed Test. SPEC §16's 'links the editor's user'.", on_delete=django.db.models.deletion.CASCADE, related_name='flow_preview_links', to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_links', to='flows.flow')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'channels_flow_preview_link',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='previewlink_expires_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
