# Generated by Django 5.2.17 on 2026-08-23 09:43

import apps.common.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_flowpreviewlink'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSettings',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('help_text_body', models.TextField(blank=True, default='', help_text='Sent when a contact texts HELP. Blank uses the default wording.')),
                ('opt_out_confirmation', models.TextField(blank=True, default='', help_text='Sent once when a contact texts STOP. Blank uses the default wording.')),
                ('opt_in_confirmation', models.TextField(blank=True, default='', help_text='Sent when a contact texts START to resubscribe. Blank uses the default wording.')),
                ('per_segment_cost', models.DecimalField(blank=True, decimal_places=5, help_text="What one segment costs on this account, for the composer's estimate. A hint, never a meter.", max_digits=8, null=True)),
                ('a2p_brand_registered', models.BooleanField(default=False)),
                ('a2p_campaign_approved', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'channels_sms_settings',
                'constraints': [models.UniqueConstraint(fields=('workspace',), name='smssettings_unique_workspace')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
