# Generated by Django 5.2.17 on 2026-08-23 09:44

import apps.common.uuid7
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0002_flowpreviewlink"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppCostHint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="ISO 4217 code, for display only. Nothing converts between currencies.",
                        max_length=3,
                    ),
                ),
                ("marketing", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=8)),
                ("utility", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=8)),
                ("authentication", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=8)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "channels_whatsapp_cost_hint",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("workspace",), name="whatsappcosthint_unique_workspace")
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Meta's template name: lowercase letters, digits and underscores.", max_length=512
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en_US", help_text="Meta's language code, e.g. en_US or de.", max_length=10
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing"),
                            ("utility", "Utility"),
                            ("authentication", "Authentication"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "body_structure",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Header/body/footer/buttons with {{n}} placeholders. See the class docstring.",
                    ),
                ),
                (
                    "meta_template_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Meta's id for this template. Empty until it has been submitted.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "In review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "rejected_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Meta's stated reason, shown to the operator. Provider-supplied: escape on render.",
                        max_length=500,
                    ),
                ),
                (
                    "channel_connection",
                    models.ForeignKey(
                        help_text="The WhatsApp connection whose WABA this template was submitted to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_templates",
                        to="channels.channelconnection",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "channels_whatsapp_template",
                "ordering": ["name", "language"],
                "indexes": [models.Index(fields=["status"], name="whatsapptemplate_status_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel_connection", "name", "language"), name="whatsapptemplate_unique_name_language"
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
