# Generated by Django 5.2.17 on 2026-08-23 09:52

import apps.common.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Re-parented onto 0003 when L5-D's sms_settings landed there first.
        # Two migrations sharing 0002 as a parent is two leaf nodes, which Django
        # refuses to migrate at all — and this one had never been applied
        # anywhere outside its own branch, so moving it is honest where a merge
        # migration would just record the collision.
        ('channels', '0003_sms_settings'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=320)),
                ('reason', models.CharField(choices=[('hard_bounce', 'Hard bounce'), ('soft_bounce', 'Repeated soft bounce'), ('complaint', 'Spam complaint'), ('unsubscribe', 'Unsubscribed'), ('manual', 'Added by hand')], max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=200)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_suppressions', to='channels.channelconnection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'channels_email_suppression',
                'ordering': ['address'],
                'indexes': [models.Index(fields=['workspace', 'address'], name='emailsuppress_ws_addr_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'address'), name='emailsuppression_unique_workspace_address')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
