# Generated by Django 5.2.17 on 2026-08-23 19:52

import apps.common.uuid7
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0005_emailsuppression'),
        ('contacts', '0003_contact_contact_ws_created_idx'),
        ('flows', '0005_handledcomment_public_reply_sent_at'),
        ('messaging', '0003_deleted_status_and_comment_consent'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('target_filter_json', models.JSONField(blank=True, default=dict)),
                ('template_variables', models.JSONField(blank=True, default=dict)),
                ('message_tag', models.CharField(blank=True, default='', max_length=64)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Null means send as soon as it is started.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('channel_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='channels.channelconnection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(blank=True, help_text="The mini-flow holding this broadcast's single-node graph.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='flows.flow')),
                ('flow_version', models.ForeignKey(blank=True, help_text='Pinned when the broadcast is scheduled, so an edit mid-send changes nothing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='flows.flowversion')),
                ('segment', models.ForeignKey(blank=True, help_text='Where target_filter_json came from. Provenance only; the document is authoritative.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='contacts.segment')),
                ('whatsapp_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='channels.whatsapptemplate')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'broadcasts_broadcast',
                'ordering': ['-created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='broadcasts.broadcast')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_recipients', to='contacts.contact')),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_recipients', to='messaging.contactchannelidentity')),
                ('message', models.ForeignKey(blank=True, help_text='The row a delivery receipt advances; how delivered/read counters stay live.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.message')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'broadcasts_recipient',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['workspace', 'status'], name='broadcast_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['status', 'scheduled_at'], name='broadcast_status_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='broadcast',
            constraint=models.CheckConstraint(condition=models.Q(('flow__isnull', True), ('whatsapp_template__isnull', True), _connector='OR'), name='broadcast_content_is_flow_or_template'),
        ),
        migrations.AddIndex(
            model_name='broadcastrecipient',
            index=models.Index(fields=['broadcast', 'status'], name='recipient_broadcast_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='broadcastrecipient',
            constraint=models.UniqueConstraint(fields=('broadcast', 'contact'), name='broadcast_recipient_unique'),
        ),
    ]
