# Generated by Django 5.2.17 on 2026-08-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0001_initial'),
        ('contacts', '0004_contacterasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_recipients', to='contacts.contact'),
        ),
    ]
