# Generated by Django 5.2.17 on 2026-10-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0002_recipient_contact_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='send_time_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
