# Generated by Django 5.2.17 on 2026-08-21 06:32

import apps.common.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('default_timezone', models.CharField(default='UTC', max_length=63)),
                ('deletion_requested_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organizations_organization',
                'ordering': ['name'],
            },
        ),
    ]
