# Generated by Django 5.2.17 on 2026-08-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='notificationdelivery',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
